services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: blep
      POSTGRES_PASSWORD: blep
      POSTGRES_DB: blep
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "blep"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    build: ./backend
    environment:
      DATABASE_URL: postgres://blep:blep@db:5432/blep
    entrypoint: ["npm", "run", "migrate:up"]
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://blep:blep@db:5432/blep
      PORT: 4000
      CORS_ORIGINS: http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
